### ISSUE TITLE
Standardize Grafana dashboards

### ISSUE THREAD

**Issue by sguruvar** [aws-samples/coast-grafana-cost-intelligence-dashboards#33]
As a COAST Admin, I want to standardize Grafana dashboards the way it was done for auto_scaling here. https://github.com/aws-samples/coast-grafana-cost-intelligence-dashboards/tree/main/grafana_dashboards

**Comment by pelgrim** [comment]
@sguruvar , this issue looks like this one: https://github.com/aws-samples/coast-grafana-cost-intelligence-dashboards/issues/2

It was closed but the issue still remains, and I'm working on that already. If you have done something, let's talk and merge our efforts.

**Comment by sguruvar** [comment]
@pelgrim I think this issue I opened more in terms of standardizing the structure of folder, file etc not necessarily inside the grafana dashboards. So i think we should be good. Lets talk more during the next connect

**Comment by pelgrim** [comment]
@sguruvar you are correct. I will reopen the other issue, this time with a different title.
