### ISSUE TITLE
Error deleting Athena workgroup

### ISSUE THREAD

**Issue by pelgrim** [aws-samples/coast-grafana-cost-intelligence-dashboards#9]
When deleting the CloudFormation stack, the following error is raised when deleting the Athena workgroup:

```
Resource handler returned message: "Invalid request provided: WorkGroup ... is not empty (Service: Athena, Status Code: 400, Request ID: ...)" (RequestToken: 1..., HandlerErrorCode: InvalidRequest)
```

**Comment by amazonchris** [comment]
RecursiveDeleteOption to true.

I also propose that we add PublishCloudWatchMetricsEnabled: true

Source:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-workgroup.html

**Comment by amazonchris** [comment]
PR Merged

**Comment by amazonchris** [comment]
PR merged
